export const FriendProfileData = [
  {
    name: '김민수',
    accountName: '바보',
    profileImage: require('../../assets/images/profile4.jpeg'),
    posts: 30,
    followers: 10,
    following: 100,
    follow: false,
  },
  {
    name: '임나연',
    accountName: '트와이스 넘버원',
    profileImage: require('../../assets/images/profile2.jpeg'),
    posts: 24,
    followers: 400,
    following: 40,
    follow: true,
  },
  {
    name: '김민영',
    accountName: '천재님',
    profileImage: require('../../assets/images/profile3.jpeg'),
    posts: 22,
    followers: 234,
    following: 100,
    follow: true,
  },
  {
    name: '정수지',
    accountName: '그냥',
    profileImage: require('../../assets/images/profile1.jpeg'),
    posts: 26,
    followers: 265,
    following: 240,
    follow: true,
  },
  {
    name: '윤성희',
    accountName: '저냥',
    profileImage: require('../../assets/images/profile5.jpeg'),
    posts: 28,
    followers: 240,
    following: 120,
    follow: true,
  },
  {
    name: '김은빈',
    accountName: '보통',
    profileImage: require('../../assets/images/post1.jpeg'),
    posts: 29,
    followers: 432,
    following: 323,
    follow: false,
  },
  {
    name: '고길동',
    accountName: '고생길',
    profileImage: require('../../assets/images/post2.jpeg'),
    posts: 21,
    followers: 20,
    following: 100,
    follow: false,
  },
  {
    name: '아이유',
    accountName: '싱글가수',
    profileImage: require('../../assets/images/post3.jpeg'),
    posts: 20,
    followers: 899,
    following: 100,
    follow: true,
  },
  {
    name: '배현진',
    accountName: '정치인',
    profileImage: require('../../assets/images/post4.jpeg'),
    posts: 22,
    followers: 300,
    following: 150,
    follow: false,
  },
  {
    name: '이예경',
    accountName: '고양이',
    profileImage: require('../../assets/images/post5.jpeg'),
    posts: 21,
    followers: 190,
    following: 170,
    follow: false,
  },
  {
    name: '권은비',
    accountName: '가수',
    profileImage: require('../../assets/images/post6.jpeg'),
    posts: 51,
    followers: 768,
    following: 423,
    follow: true,
  },
  {
    name: '이나은',
    accountName: '에이프릴',
    profileImage: require('../../assets/images/post7.jpeg'),
    posts: 30,
    followers: 432,
    following: 234,
    follow: true,
  },
  {
    name: '피카소',
    accountName: '화가많아',
    profileImage: require('../../assets/images/post8.jpeg'),
    posts: 70,
    followers: 999,
    following: 432,
    follow: false,
  },
];
